### ISSUE TITLE
合约列表按照搜索框输入模糊匹配的合约名查询时，查出数据为空，实际有数据

### ISSUE THREAD

**Issue by Skkypy** [WeBankBlockchain/WeBASE-Node-Manager#301]
[ContractMapper.xml](https://github.com/WeBankFinTech/WeBASE-Node-Manager/blob/master/src/main/resources/mapper/ContractMapper.xml)中的`countOfContract`语句有合约模糊查询，`listOfContract`语句没有模糊查询。建议保持一致并忽略大小写，类似： `and lower(contract_name) like CONCAT('%',lower(#{contractName}),'%')`

**Comment by CodingCattwo** [comment]
已修复，感谢Issue~
