### ISSUE TITLE
tb_front建表语句status描述问题

### ISSUE THREAD

**Issue by Skkypy** [WeBankBlockchain/WeBASE-Node-Manager#435]
`tb_front`建表语句：
` status int(11) DEFAULT 1 COMMENT '前置服务状态：0，未创建；1，停止；2，启动；',`
实际应为：
` status int(11) DEFAULT 1 COMMENT '前置服务状态：0，未创建；1，启动；2，停止；',`
请验证。

**Comment by CodingCattwo** [comment]
感谢反馈，可以提交一个Pull  Request修复代码中的comment~
