### ISSUE TITLE
webase删除群组数据，当删除表tb_trans_bash数据时删除很慢。

### ISSUE THREAD

**Issue by git-jacky-man** [WeBankBlockchain/WeBASE-Node-Manager#437]
当删除数据量很大，这次需要删除的数据有1900万条交易，删除群组数据时是按照1000条循环删除，非常的慢，没有触发一次性删除

**Comment by CodingCattwo** [comment]
此处在新版本会优化为直接drop群组对应的区块和交易表以优化交易量大时的删除速度问题。
如果需要重建数据数据，可以暂时先直接到db中drop数据表或者重命名表后，重建新的空表
