### ISSUE TITLE
节点状态：区块链搭建之后，高度为 0  === 但是按照代码逻辑，这种属于异常状态？

### ISSUE THREAD

**Issue by Youbaiwan** [WeBankBlockchain/WeBASE-Node-Manager#463]
![image](https://user-images.githubusercontent.com/49031861/191444086-dd528e37-5476-49aa-b654-ec06d2e3fc08.png)

**Comment by CodingCattwo** [comment]
此处会动态判断节点是否异常，判断的大致逻辑为：节点的块高持续在变化，或者pbftView持续在变化，即为正常
